import Head from 'next/head'
import { Inter } from '@next/font/google'
import HeroSection from '@/components/hero/HeroSection'
import HomePage from '@/components/home/HomePage'


const inter = Inter({ subsets: ['latin'] })

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeroSection/>
        <HomePage data={data}/>
      </main>
    </>
  )
}

export async function getServerSideProps() {
  const { events_categories } = await import ('/data/data.json')

  return {
    props: {
      data: events_categories
    }
  }
}